# Tabby Shaders - Item IDs for colored hand light
# Copyright (c) 2026 Avie29 - Licensed under CC BY-NC 4.0 (see LICENSE)
# Same numbers as the light sources in block.properties (colors: lib/light_colors.glsl)

item.10101 = torch lantern campfire jack_o_lantern
item.10102 = soul_torch soul_lantern soul_campfire
item.10103 = redstone_torch
item.10104 = glowstone shroomlight ochre_froglight copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb \
    waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb
item.10105 = sea_lantern beacon end_rod conduit
item.10106 = lava_bucket magma_block
item.10107 = amethyst_cluster large_amethyst_bud crying_obsidian respawn_anchor
item.10108 = copper_torch copper_lantern exposed_copper_lantern weathered_copper_lantern oxidized_copper_lantern \
    waxed_copper_lantern waxed_exposed_copper_lantern waxed_weathered_copper_lantern waxed_oxidized_copper_lantern
item.10109 = verdant_froglight
item.10110 = pearlescent_froglight
item.10111 = glow_lichen glow_berries
item.10112 = sea_pickle
item.10113 = creaking_heart
item.10114 = candle white_candle orange_candle magenta_candle light_blue_candle yellow_candle lime_candle pink_candle \
    gray_candle light_gray_candle cyan_candle purple_candle blue_candle brown_candle green_candle red_candle black_candle
